from ccpn.framework.lib.Plugin import Plugin
from ccpn.ui.gui.modules.CcpnModule import CcpnModule


class AutoGeneratedDevPlugin(Plugin):
  PLUGINNAME = 'Development Plugin...Custom Gui'
  guiModule = CcpnModule
