# Push release/updates/edge to github

image: atlassian/default-image:3

definitions:
  services:
    docker:
      memory: 1024

  steps:
    - step: &Push-to-GitHub-Main
        name: Push code changes to GitHub
        services:
          - docker
        caches:
          - docker
        script:
          - git remote add github "https://$GITHUB_TOKEN@github.com/ccpnmr/analysis.git"
          - git push --force github main

    - step: &Push-to-GitHub-Updates
        name: Push code changes to GitHub
        services:
          - docker
        caches:
          - docker
        script:
          - git remote add github "https://$GITHUB_TOKEN@github.com/ccpnmr/analysis.git"
          - git push --force github updates

    - step: &Push-to-GitHub-Edge
        name: Push code changes to GitHub
        services:
          - docker
        caches:
          - docker
        script:
          - git remote add github "https://$GITHUB_TOKEN@github.com/ccpnmr/analysis-private.git"
          - git push --force github $BITBUCKET_BRANCH

pipelines:
  branches:
    # release branches
    "[0-9].[0-9].[0-9]":
      - step: *Push-to-GitHub-Main
    "[0-9].[0-9].[0-9][0-9]":
      - step: *Push-to-GitHub-Main
    "[0-9].[0-9][0-9].[0-9]":
      - step: *Push-to-GitHub-Main
    "[0-9].[0-9][0-9].[0-9][0-9]":
      - step: *Push-to-GitHub-Main

    # release + hotfixes to update server
    "[0-9].[0-9].[0-9]-updates":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9].[0-9][0-9]-updates":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9][0-9].[0-9]-updates":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9][0-9].[0-9][0-9]-updates":
      - step: *Push-to-GitHub-Updates

    "[0-9].[0-9].[0-9]-updates[0-9]":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9].[0-9][0-9]-updates[0-9]":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9][0-9].[0-9]-updates[0-9]":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9][0-9].[0-9][0-9]-updates[0-9]":
      - step: *Push-to-GitHub-Updates

    # release candidates
    "[0-9].[0-9].[0-9]-edge":
      - step: *Push-to-GitHub-Edge
    "[0-9].[0-9].[0-9][0-9]-edge":
      - step: *Push-to-GitHub-Edge
    "[0-9].[0-9][0-9].[0-9]-edge":
      - step: *Push-to-GitHub-Edge
    "[0-9].[0-9][0-9].[0-9][0-9]-edge":
      - step: *Push-to-GitHub-Edge
