# Push release/updates/edge to github

image: atlassian/default-image:3

definitions:
  services:
    docker:
      memory: 1024

  steps:
    - step: &setup
        name: load scripts
        services:
          - docker
        caches:
          - docker
        script:
          - echo 'git remote add github "https://$GITHUB_TOKEN@github.com/ccpnmr/${1}"' >> ./bitbucket_to_github.sh
          - echo 'git push --force github ${2}' >> ./bitbucket_to_github.sh
        artifacts:
          - ./bitbucket_to_github.sh

    - step: &Push-to-GitHub-Main
        name: Push code changes to GitHub
        services:
          - docker
        caches:
          - docker
        script:
          - /bin/bash internal/scripts/bitbucket_to_github.sh analysis main

    - step: &Push-to-GitHub-Updates
        name: Push code changes to GitHub
        services:
          - docker
        caches:
          - docker
        script:
          - /bin/bash internal/scripts/bitbucket_to_github.sh analysis updates

    - step: &Push-to-GitHub-Edge
        name: Push code changes to GitHub
        services:
          - docker
        caches:
          - docker
        script:
          - /bin/bash /tmp/scripts/bitbucket_to_github.sh analysis-private $BITBUCKET_BRANCH

pipelines:
  branches:
    # release branches
    "[0-9].[0-9].[0-9]":
      - step: *Push-to-GitHub-Main
    "[0-9].[0-9].[0-9][0-9]":
      - step: *Push-to-GitHub-Main
    "[0-9].[0-9][0-9].[0-9]":
      - step: *Push-to-GitHub-Main
    "[0-9].[0-9][0-9].[0-9][0-9]":
      - step: *Push-to-GitHub-Main

    # release + hotfixes to update server
    "[0-9].[0-9].[0-9]-updates":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9].[0-9][0-9]-updates":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9][0-9].[0-9]-updates":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9][0-9].[0-9][0-9]-updates":
      - step: *Push-to-GitHub-Updates

    "[0-9].[0-9].[0-9]-updates[0-9]":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9].[0-9][0-9]-updates[0-9]":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9][0-9].[0-9]-updates[0-9]":
      - step: *Push-to-GitHub-Updates
    "[0-9].[0-9][0-9].[0-9][0-9]-updates[0-9]":
      - step: *Push-to-GitHub-Updates

    # release candidates
    "[0-9].[0-9].[0-9]-edge":
      - step: *setup
      - step: *Push-to-GitHub-Edge
    "[0-9].[0-9].[0-9][0-9]-edge":
      - step: *setup
      - step: *Push-to-GitHub-Edge
    "[0-9].[0-9][0-9].[0-9]-edge":
      - step: *setup
      - step: *Push-to-GitHub-Edge
    "[0-9].[0-9][0-9].[0-9][0-9]-edge":
      - step: *setup
      - step: *Push-to-GitHub-Edge
