# mypy.ini

[mypy]
# Specify the Python version your code is written for.
# This should match the Python version in your Miniconda environment.
python_version = 3.10

# Treat all type hints as strings, enabling forward references and
# preventing import cycle issues during type checking.
# This should also be set in your Python files with 'from __future__ import annotations'.
implicit_reexport = False
implicit_optional = True
explicit_package_bases = True
check_untyped_defs = True

# The local mypy in homebrew is being used as it doesn't require mypy to be in the conda environment;
# however, this requires that the python-executable needs to be specified.
python_executable = miniconda/bin/python

# Furthermore, the source-paths need to match the pycharm source-paths, and `explicit_package_bases`
# needs to be set, otherwise there are duplicate package errors :| not sure exactly why.
mypy_path = src/python:src/python/chemBuild:internal/src/python
