#!/usr/bin/env bash
# Remove quarantine from apps

APP_LIST=(Assign Screen Metabolomics)

removeQuarantine() {
	QUAR="com.apple.quarantine"

	for APP in ${APP_LIST[*]}; do
		CHECK_APP="./Analysis${APP}.app/"
		echo ${CHECK_APP}
		if [[ $(xattr -l ${CHECK_APP}) == *${QUAR}* ]]; then
	  	 	echo "Removing Quarantine from ${CHECK_APP}"
		 	# need to find the unlocked file here and unlock that
			# if run from inside the .app
	  		xattr -d -r ${QUAR} ${CHECK_APP}
		fi
	done
}

case "$OSTYPE" in
  solaris*) echo "SOLARIS" ;;
  darwin*)  echo "OSX"
	    removeQuarantine ;; 
  linux*)   echo "LINUX" ;;
  bsd*)     echo "BSD" ;;
  msys*)    echo "WINDOWS" ;;
  *)        echo "unknown: $OSTYPE" ;;
esac

echo "done."
