#!/usr/bin/env bash

export CCPNMR_TOP_DIR="$(cd "$PWD"/../../..; pwd)"
echo ">>> CCPNMR_TOP_DIR=${CCPNMR_TOP_DIR}"

ANALYSIS="${CCPNMR_TOP_DIR}"/src/python/ccpn/AnalysisScreen
echo ">>> ANALYSIS=${ANALYSIS}"

source "${CCPNMR_TOP_DIR}"/bin/paths.sh
"${ANACONDA3}"/bin/python -W ignore::DeprecationWarning "${ANALYSIS}" $*
