#!/usr/bin/env pyXplor

opts,args = xplor.parseArguments()

nefFilename,talosPredFile,talosPreAllFile = args[:3]

from nefTools import readNEF 
nef = readNEF(nefFilename) # generates PSF information

#detect multimers
segids=['A']
from selectTools import getSegsResidues
segsResidues=getSegsResidues()
if len( segsResidues ) > 1:
    for segid in segsResidues:
        if segid=='A':
            continue
        if segsResidues[segid] == segsResidues['A']:
            segids.append( segid )
            pass
        pass
    if len(segids)>1:
        print(f"found a symmetric {len(segids)}-mer")
        pass
    pass
        

import iupacNaming
iupacNaming.toIUPAC()  #switch to IUPAC naming

restraints=""
for segid in segids:
    from talosTools import convertTalosN
    restraints += convertTalosN(predFile="pred.tab",
                                predAllFile="predAll.tab",
                                widthPadding= 5, # degrees
                                minWidth = 20, # degrees
                                useWeights=True,
                                segName=segid,
                                omitResids=[],
                                )
    pass

import protocol
protocol.initDihedrals(string=restraints)

import os
rootName=os.path.splitext(nefFilename)[0]

from torsionPotTools import Xplor_writeNEF
newNEF = open(rootName+"_new.nef","w")
newNEF.write( open(nefFilename).read() )
newNEF.write( "\n#dihedral restraints generated by Talos-N\n" )
newNEF.write( Xplor_writeNEF("nef_dihedral_restraint_list_1",
                             origin="TALOS-N") )



