"""
This module defines base classes for Series Analysis
"""
#=========================================================================================
# Licence, Reference and Credits
#=========================================================================================
__copyright__ = "Copyright (C) CCPN project (https://www.ccpn.ac.uk) 2014 - 2022"
__credits__ = ("Ed Brooksbank, Joanna Fox, Victoria A Higman, Luca Mureddu, Eliza Płoskoń",
               "Timothy J Ragan, Brian O Smith, Gary S Thompson & Geerten W Vuister")
__licence__ = ("CCPN licence. See https://ccpn.ac.uk/software/licensing/")
__reference__ = ("Skinner, S.P., Fogh, R.H., Boucher, W., Ragan, T.J., Mureddu, L.G., & Vuister, G.W.",
                 "CcpNmr AnalysisAssign: a flexible platform for integrated NMR analysis",
                 "J.Biomol.Nmr (2016), 66, 111-124, http://doi.org/10.1007/s10858-016-0060-y")
#=========================================================================================
# Last code modification
#=========================================================================================
__modifiedBy__ = "$modifiedBy: Luca Mureddu $"
__dateModified__ = "$dateModified: 2022-03-07 10:19:03 +0000 (Mon, March 07, 2022) $"
__version__ = "$Revision: 3.1.0 $"
#=========================================================================================
# Created
#=========================================================================================
__author__ = "$Author: Luca Mureddu $"
__date__ = "$Date: 2022-02-02 14:08:56 +0000 (Wed, February 02, 2022) $"
#=========================================================================================
# Start of code
#=========================================================================================


from ccpn.framework.lib.experimentAnalysis.SeriesAnalysisABC import SeriesAnalysisABC
import ccpn.framework.lib.experimentAnalysis.SeriesAnalysisVariables as sv
from ccpn.framework.lib.experimentAnalysis.RelaxationFittingModels import _registerRelaxationModels
from ccpn.util.Logging import getLogger


class RelaxationAnalysisBC(SeriesAnalysisABC):
    """
    Relaxation Analysis Non-Gui module.
    """
    seriesAnalysisName = sv.RelaxationAnalysis

    def __init__(self, application):
        super().__init__(application)
        _registerRelaxationModels()


    @staticmethod
    def newDataTableFromSpectrumGroup(spectrumGroup, seriesTableType=sv.RELAXATION_INPUT_FRAME,
                                      thePeakProperty=sv._HEIGHT,
                                      dataTableName=sv.RELAXATION_INPUT_FRAME, **kwargs):
        """
        :param spectrumGroup: object of type SpectrumGroup
        :param seriesTableType: str, One of sv.INPUT_SERIESFRAME_TYPES e.g.: sv.CSM_INPUT_FRAME
        :param dataTableName: str, name for a newData table object. Autogenerated if none
        :param kwargs: any key:value for creating the new DataTable object.
        :return:
        """
        from ccpn.framework.lib.experimentAnalysis.SeriesTablesBC import INPUT_RELAXATION_SERIESFRAMES_DICT, _mergeRowsByHeaders
        project = spectrumGroup.project
        seriesFrameCLS = INPUT_RELAXATION_SERIESFRAMES_DICT.get(seriesTableType)
        if not seriesFrameCLS:
            raise RuntimeError(f'Cannot find SeriesFrame for {seriesTableType}.')
        seriesFrame = seriesFrameCLS()
        seriesFrame.buildFromSpectrumGroup(spectrumGroup=spectrumGroup, thePeakProperty=thePeakProperty)
        seriesFrame = _mergeRowsByHeaders(seriesFrame, sv.GROUPPING_HEADERS, dropColumnNames=sv.ATOM_NAME)
        dataTable = project.newDataTable(name=dataTableName, data=seriesFrame)
        return dataTable


    def fitInputData(self, *args, **kwargs):
        """
        Perform the registered FittingModels to the inputDataTables and add the outputs to a newDataTable or
         override last available.
        :param args:
        :param kwargs:
            :key: fittingModels:    list of fittingModel classes (not initialised).So to use only the specif given,
                                    rather than all available.
            :key: overrideOutputDataTables: bool, True to rewrite the output result in the last available dataTable.
                                    When multiple fittingModels are available, each will output in a different dataTable
                                    according to its definitions.
        :return: None
        """
        getLogger().warning(sv.UNDER_DEVELOPMENT_WARNING)

        if not self.inputDataTables:
            raise RuntimeError('Cannot run any fitting models. Add a valid inputData first')

        fittingModels = self.fittingModels or kwargs.get(sv.FITTING_MODELS, [])
        ovverideOutputDataTable = kwargs.get(sv.OVERRIDE_OUTPUT_DATATABLE, True)
        for model in fittingModels:
            fittingModel = model()
            inputDataTable = self.inputDataTables[-1]
            outputFrame = fittingModel.fitSeries(inputDataTable.data)
            outputName = f'{inputDataTable.name}_output_{fittingModel.ModelName}'
            outputDataTable = self._fetchOutputDataTable(name=outputName, seriesFrameType=sv.CSM_OUTPUT_FRAME,
                                                   overrideExisting=ovverideOutputDataTable)
            outputDataTable.data = outputFrame
            self.addOutputData(outputDataTable)






