"""
This module defines base classes for Series Analysis
"""
#=========================================================================================
# Licence, Reference and Credits
#=========================================================================================
__copyright__ = "Copyright (C) CCPN project (https://www.ccpn.ac.uk) 2014 - 2022"
__credits__ = ("Ed Brooksbank, Joanna Fox, Victoria A Higman, Luca Mureddu, Eliza Płoskoń",
               "Timothy J Ragan, Brian O Smith, Gary S Thompson & Geerten W Vuister")
__licence__ = ("CCPN licence. See https://ccpn.ac.uk/software/licensing/")
__reference__ = ("Skinner, S.P., Fogh, R.H., Boucher, W., Ragan, T.J., Mureddu, L.G., & Vuister, G.W.",
                 "CcpNmr AnalysisAssign: a flexible platform for integrated NMR analysis",
                 "J.Biomol.Nmr (2016), 66, 111-124, http://doi.org/10.1007/s10858-016-0060-y")
#=========================================================================================
# Last code modification
#=========================================================================================
__modifiedBy__ = "$modifiedBy: Luca Mureddu $"
__dateModified__ = "$dateModified: 2022-02-11 17:19:54 +0000 (Fri, February 11, 2022) $"
__version__ = "$Revision: 3.1.0 $"
#=========================================================================================
# Created
#=========================================================================================
__author__ = "$Author: Luca Mureddu $"
__date__ = "$Date: 2022-02-02 14:08:56 +0000 (Wed, February 02, 2022) $"
#=========================================================================================
# Start of code
#=========================================================================================


from abc import ABC, abstractmethod
from ccpn.util.OrderedSet import OrderedSet
from ccpn.core.DataTable import DataTable
from ccpn.core.SpectrumGroup import SpectrumGroup

class SeriesAnalysisABC(ABC):
    """
    The top level class for SeriesAnalysis modules.
    """

    seriesAnalysisName = ''
    fittingModels = OrderedSet()

    @classmethod
    def inputData(cls):
        """
        Get the attached input DataTable
        Lists of DataTables.
        Add decorator to ensure the input dataFrame is of the write type as in the subclass.
        (especially when restoring a project)
        """
        pass

    @classmethod
    def outputData(cls):
        """
        Get the attached output DataTable
        Lists of DataTables?
        """
        pass

    @classmethod
    def fit(self, data) -> DataTable:
        """
        ovveride on custom implementation
        :param data: TableFrame
        :return: TableFrame

        Fit should create always a new output datatable or overwrite existing?
        """
        return data

    @classmethod
    def registerFittingModel(cls, fittingModel):
        """
        A method to register a FittingModel object.
        See the FittingModelABC for more information
        """
        from ccpn.framework.lib.experimentAnalysis.FittingModelABC import FittingModelABC
        if not isinstance(fittingModel, FittingModelABC):
            raise ValueError(f'The provided {fittingModel} is not of instance {FittingModelABC}.')
        cls.fittingModels.add(fittingModel)

    @classmethod
    def deRegisterFittingModel(cls, fittingModel):
        """
        A method to de-register a fitting Model
        """
        cls.fittingModels.discard(fittingModel)

    def getFittingModelByName(self, modelName):
        """
        Convenient method to get a registered FittingModel Object  by its name
        :param modelName: str
        :return:
        """
        for fittingModel in self.fittingModels:
            if fittingModel.ModelName == modelName:
                return fittingModel

    @staticmethod
    def newDataTableFromSpectrumGroup(spectrumGroup:SpectrumGroup, seriesTableType:str,
                                      dataTableName:str=None, **kwargs):
        """
        :param spectrumGroup: object of type SpectrumGroup
        :param seriesTableType: str, One of sv.INPUT_SERIESFRAME_TYPES e.g.: sv.RELAXATION_INPUT_FRAME
        :param dataTableName: str, name for a newData table object. Autogenerated if none
        :param kwargs:
        :return:
        """
        pass

    @classmethod
    def exportToFile(cls, path, fileType, *args, **kwargs):
        """
        A method to export to an external File
        """
        pass

    def __init__(self, application):

        self.application = application
        self.project = self.application.project


    def __str__(self):
        return f'<{self.__class__.__name__}: {self.seriesAnalysisName}>'

    __repr__ = __str__



