#=========================================================================================
# Licence, Reference and Credits
#=========================================================================================
__copyright__ = "Copyright (C) CCPN project (http://www.ccpn.ac.uk) 2014 - 2017"
__credits__ = ("Wayne Boucher, Ed Brooksbank, Rasmus H Fogh, Luca Mureddu, Timothy J Ragan"
               "Simon P Skinner & Geerten W Vuister")
__licence__ = ("CCPN licence. See http://www.ccpn.ac.uk/v3-software/downloads/license"
               "or ccpnmodel.ccpncore.memops.Credits.CcpnLicense for licence text")
__reference__ = ("For publications, please use reference from http://www.ccpn.ac.uk/v3-software/downloads/license"
               "or ccpnmodel.ccpncore.memops.Credits.CcpNmrReference")
#=========================================================================================
# Last code modification
#=========================================================================================
__modifiedBy__ = "$modifiedBy: Luca Mureddu $"
__dateModified__ = "$dateModified: 2017-05-28 10:28:42 +0000 (Sun, May 28, 2017) $"
__version__ = "$Revision: 3.0.b1 $"
#=========================================================================================
# Created
#=========================================================================================
__author__ = "$Author: Luca Mureddu $"
__date__ = "$Date: 2017-05-28 10:28:42 +0000 (Sun, May 28, 2017) $"
#=========================================================================================
# Start of code
#=========================================================================================





from ccpn.framework.lib.Pipe import Pipe
from ccpn.pipes.examples.DemoGuiPipe import DemoGuiPipe
from ccpn.pipes.examples.DemoAutoGeneratedGuiPipe import AutoGeneratedGuiPipeDemo

class DemoPipe1(Pipe):

  guiPipe = DemoGuiPipe
  pipeName = DemoGuiPipe.pipeName


  def runPipe(self, data):

    print(data)





class DemoPipe2(Pipe):
  'Demo with autoGenerated gui'

  guiPipe = AutoGeneratedGuiPipeDemo
  pipeName = DemoGuiPipe.pipeName


  def runPipe(self, data):

    print(data)