#=========================================================================================
# Licence, Reference and Credits
#=========================================================================================
__copyright__ = "Copyright (C) CCPN project (https://www.ccpn.ac.uk) 2014 - 2023"
__credits__ = ("Ed Brooksbank, Joanna Fox, Victoria A Higman, Luca Mureddu, Eliza Płoskoń",
               "Timothy J Ragan, Brian O Smith, Gary S Thompson & Geerten W Vuister")
__licence__ = ("CCPN licence. See http://www.ccpn.ac.uk/v3-software/downloads/license",
               )
__reference__ = ("Skinner, S.P., Fogh, R.H., Boucher, W., Ragan, T.J., Mureddu, L.G., & Vuister, G.W.",
                 "CcpNmr AnalysisAssign: a flexible platform for integrated NMR analysis",
                 "J.Biomol.Nmr (2016), 66, 111-124, http://doi.org/10.1007/s10858-016-0060-y"
                 )
#=========================================================================================
# Last code modification
#=========================================================================================
__modifiedBy__ = "$modifiedBy: Geerten Vuister $"
__dateModified__ = "$dateModified: 2023-10-08 10:59:55 +0100 (Sun, October 08, 2023) $"
__version__ = "$Revision: 3.2.0 $"
#=========================================================================================
# Created
#=========================================================================================
__author__ = "$Author: geertenv $"
__date__ = "$Date: 2018-05-14 10:28:41 +0000 (Fri, April 07, 2017) $"
#=========================================================================================
# Start of code
#=========================================================================================

class TraitJsonHandlerBase():
    """Base class for all Trait json handlers;

     Any jsonHandler class must derive from TraitJsonHandlerBase and can subclass
     two  methods:

         encode(value) which returns a json serialisable object
         decode(value) which uses value to generate and set the new (or modified) obj

     The jsonHandler instance has two (useful?) attributes:
         self.trait: The trait instance, whose value, i.e. obj.traitName, is en-/de-coded
         self.obj: The trait containing object

     Example:

         class myHandler(TraitJsonHandlerBase):
               def encode(self, value):
                   "returns a json serialisable object"
                   -- some action on value --
                   return value

               def decode(self, value):
                   "uses value to generate and return the new (or modified) value"
                   newValue =  --- some action using value ---
                   return value
    """
    def __init__(self, obj, trait):
        """
        Initialise self, store object and trait
        :param obj: the object instance to encode a value from,
        :param trait: the trait instance of the object klass
        """
        self.obj = obj
        self.trait = trait

    def encode(self, value):
        """Encode the value for json
        :param value: the value to encode
        :returns the encoded value as a json serialisable object
        """
        # This is a stub that does nothing
        return value

    def decode(self, value):
        """Decode value as generated by encode and obtained from json
        :returns decoded value
        """
        # This is stub that does nothing
        return value


class ContainerJsonHandlerABC(TraitJsonHandlerBase):
    """Abstract base class for container types; i.e. list, dict.
    Handles (optionally) recursion of list/dict/set/tuple-like traits
    Each value of the (key,value) pairs must of CcpNmrJson (sub-)type
    """
    #--------------------------------------------------------------------------------------------
    # to be subclassed
    #--------------------------------------------------------------------------------------------
    klass = None        # The class to be handled
    #--------------------------------------------------------------------------------------------
    # end to be subclassed

    def getJsonItemHandler(self, parent, item):
        """:return A jsonHandler instance for the child-item or None which
        indicates not handling is needed (or can be defined)
        Could be subclassed;
        """
        # local import to avoid cycles
        from ccpn.util.traits.CcpNmrTraits import OWTraits, Any
        from ccpn.util.traits.CcpNmrJson import CcpNmrJson

        _trait = self.trait.itemTrait or self.trait.valueTrait
        if _trait is not None:
            pass

        elif isinstance(item, CcpNmrJson):
            # for encode
            _trait = OWTraits(allow_none=True)

        elif CcpNmrJson._isEncodedObject(item):
            # for decode
            _trait = OWTraits(allow_none=True)

        else:
            pass

        if _trait is None:
            return None
        else:
            return _trait.getJsonHandler(obj=parent)

    def encodeItem(self, parent, item):
        """encode item of the container value;
        getHandler will be checking for CcpNmrJson instances and defined handlers
        :parameter parent: the container object; e.g. a list or dict, ...
        :parameter item: the item to be encoded from the container
        :return Encoded item
        Can be subclassed
        """
        if item is None:
            return None

        if (itemHandler := self.getJsonItemHandler(parent, item)) is not None:
            newValue = itemHandler.encode(item)

        else:
            newValue = item

        return newValue

    def decodeItem(self, parent, item):
        """decode item of the container parent
        getHandler will be checking for CcpNmrJson instances and defined handlers
        :parameter parent: the container object; e.g. a list or dict, ...
        :parameter item: the item to be encoded from the container
        :return Decoded item
        Can be subclassed
        """
        if item is None:
            return None

        if (itemHandler := self.getJsonItemHandler(parent, item)) is not None:
            newValue = itemHandler.decode(item)

        else:
            newValue = item

        return newValue


class DictTraitJsonHandlerABC(ContainerJsonHandlerABC):
    """Abstract base class to handle recursion of dict-like traits
    """

    def encode(self, theDict) -> dict:
        """Encode theDict, recursing values depending on class / trait settings

        :param theDict: a dict instance of self.klass to be encoded
        :return: A dict with (key, encoded-value) pairs
        """
        from ccpn.util.Common import classType

        if not isinstance(theDict, self.klass):
            raise RuntimeError(f'Expected instance of {classType(self.klass)}, got {classType(theDict)}')

        theList = [(key, self.encodeItem(theDict, val)) for key,val in theDict.items()]
        return dict(theList)

    def decode(self, theData) -> dict:
        """Decode theData, i.e. a dict or a list of (key,value) pairs;
        always recurse to decode values

        :param theData: dict or list with (key,value) pairs to decode
        :return: the decoded data as a dict
        """
        # previously, Dict items were not encoded as list of (key, value) tuples,
        # only RecursiveDicts and the like. Now there is no distinction, so we
        # need to check theData
        if isinstance(theData, list):
            theData = dict(theData)
        # needs recursing for each (key, value) pair
        result = [(key, self.decodeItem(theData, value)) for key, value in theData.items()]
        return dict(result)
# end class


class ListTraitJsonHandlerABC(ContainerJsonHandlerABC):
    """Abstract base class to handle recursion of list-like traits
    """
    def encode(self, theList) -> list:
        """Encode theList, recursing depending on class / trait settings

        :param theList: a list instance of self.klass to be encoded
        :return: The encoded list
        """
        from ccpn.util.Common import classType

        if not isinstance(theList, self.klass):
            raise RuntimeError(f'Expected instance of {classType(self.klass)}, got {classType(theList)}')

        result = [self.encodeItem(theList, item) for item in theList]
        return result

    def decode(self, theList):
        """Decode theList of encoded items;
        always recurse to decode items

        :param theList: list with items to decode
        :return: the decoded list
        """
        # needs decoding for each item in theList
        result = [self.decodeItem(theList, item) for item in theList]
        return result
# end class


class CcpNmrJsonClassHandlerABC(TraitJsonHandlerBase):
    """Abstract base class to handle class-like traits of the CcpNmrJson (sub-)type
    """
    # #--------------------------------------------------------------------------------------------
    # # to be subclassed
    # #--------------------------------------------------------------------------------------------
    # klass = None
    # #--------------------------------------------------------------------------------------------
    # # end to be subclassed
    # #--------------------------------------------------------------------------------------------

    def encode(self, value):
        # convert klass, of (sub-)type CcpNmrJson

        # local imports to avoid circular dependencies
        from ccpn.util.traits.CcpNmrJson import CcpNmrJson

        if isinstance(value, CcpNmrJson):
            value = value._encode()

        return value

    def decode(self, value):
        # converting value to the relevant klass instance

        # local imports to avoid circular dependencies
        from ccpn.util.traits.CcpNmrJson import CcpNmrJson

        result = value
        # check if this encoded a CcpNmrJson type object
        if CcpNmrJson._isEncodedObject(value):
            theDict = dict(value)
            result = CcpNmrJson._newObjectFromDict(theDict)

        return result
