#=========================================================================================
# Licence, Reference and Credits
#=========================================================================================
__copyright__ = "Copyright (C) CCPN project (https://www.ccpn.ac.uk) 2014 - 2023"
__credits__ = ("Ed Brooksbank, Joanna Fox, Victoria A Higman, Luca Mureddu, Eliza Płoskoń",
               "Timothy J Ragan, Brian O Smith, Gary S Thompson & Geerten W Vuister")
__licence__ = ("CCPN licence. See http://www.ccpn.ac.uk/v3-software/downloads/license",
               )
__reference__ = ("Skinner, S.P., Fogh, R.H., Boucher, W., Ragan, T.J., Mureddu, L.G., & Vuister, G.W.",
                 "CcpNmr AnalysisAssign: a flexible platform for integrated NMR analysis",
                 "J.Biomol.Nmr (2016), 66, 111-124, http://doi.org/10.1007/s10858-016-0060-y"
                 )
#=========================================================================================
# Last code modification
#=========================================================================================
__modifiedBy__ = "$modifiedBy: Geerten Vuister $"
__dateModified__ = "$dateModified: 2023-10-06 18:00:36 +0100 (Fri, October 06, 2023) $"
__version__ = "$Revision: 3.2.0 $"
#=========================================================================================
# Created
#=========================================================================================
__author__ = "$Author: geertenv $"
__date__ = "$Date: 2018-05-14 10:28:41 +0000 (Fri, April 07, 2017) $"
#=========================================================================================
# Start of code
#=========================================================================================

class TraitJsonHandlerBase():
    """Base class for all Trait json handlers;

     Any jsonHandler class must derive from TraitJsonHandlerBase and can subclass
     two  methods:

         encode(value) which returns a json serialisable object
         decode(value) which uses value to generate and set the new (or modified) obj

     The jsonHandler instance has two (useful?) attributes:
         self.trait: The trait instance, whose value, i.e. obj.traitName, is en-/de-coded
         self.obj: The trait containing object

     Example:

         class myHandler(TraitJsonHandlerBase):
               def encode(self, value):
                   "returns a json serialisable object"
                   -- some action on value --
                   return value

               def decode(self, value):
                   "uses value to generate and return the new (or modified) value"
                   newValue =  --- some action using value ---
                   return value
    """
    def __init__(self, obj, trait):
        """
        Initialise self, store object and trait
        :param obj: the object instance to encode a value from,
        :param trait: the trait instance of the object klass
        """
        self.obj = obj
        self.trait = trait

    def encode(self, value):
        """Encode the value for json
        :param value: the value to encode
        :returns the encoded value as a json serialisable object
        """
        # This is a stub that does nothing
        return value

    def decode(self, value):
        """Decode value as generated by encode and obtained from json
        :returns decoded value
        """
        # This is stub that does nothing
        return value


class ContainerJsonHandlerABC(TraitJsonHandlerBase):
    """Abstract base class for container types; i.e. list, dict.
    Handles (optionally) recursion of list/dict/set/tuple-like traits
    Each value of the (key,value) pairs must of CcpNmrJson (sub-)type
    """
    #--------------------------------------------------------------------------------------------
    # to be subclassed
    #--------------------------------------------------------------------------------------------
    klass = None        # The class to be handled
    recursion = False   # Flag to recurse if CcpNmrJson objects are encountered in the list
                        # True overrides trait instance setting
    #--------------------------------------------------------------------------------------------
    # end to be subclassed

    def _doRecurse(self) -> bool:
        """Recursion logic flag; class definition == True overrides trait instance definition
        """
        if self.recursion:
            _recursion = True
        else:
            _recursion = self.trait.recursion
        return _recursion

    def getJsonItemHandler(self):
        """:return A jsonHandler instance for the item or None
        to be subclassed; without it all container items will be unaltered
        """
        return None

    def encodeItem(self, item):
        """encode item of the container, checking for CcpNmrJson instances and jsonHandlers
        :return Encoded item
        Can be subclassed
        """
        # local imports to avoid circular dependencies
        from ccpn.util.traits.CcpNmrJson import CcpNmrJson

        if isinstance(item, CcpNmrJson):
            newValue = item._encode()

        elif (jsonHandler := self.getJsonItemHandler()) is not None:
            newValue = jsonHandler.encode(item)

        else:
            newValue = item

        return newValue

    def decodeItem(self, item):
        """decode item of the container, checking for possible CcpNmrJson encoded data and jsonHandlers
        :return Decoded item
        Can be subclassed
        """
        # local imports to avoid circular dependencies
        from ccpn.util.traits.CcpNmrJson import CcpNmrJson

        if CcpNmrJson._isEncodedObject(item):
            theDict = dict(item)
            newValue = CcpNmrJson._newObjectFromDict(theDict)

        elif (jsonHandler := self.getJsonItemHandler()) is not None:
            newValue = jsonHandler.decode(item)

        else:
            newValue = item

        return newValue


class DictTraitJsonHandlerABC(ContainerJsonHandlerABC):
    """Abstract base class to handle (optionally) recursion of dict-like traits
    Each value of the (key,value) pairs must of CcpNmrJson (sub-)type
    """

    def _getJsonItemHandler(self):
        """:return A jsonHandler instance for the item or None
        """
        if self.trait.valueTrait is not None:
            return self.trait.valueTrait.getJsonHandler(obj=self.obj)
        else:
            return None

    def encode(self, theDict):
        """Encode theDict, optionally recursing depending on class / trait settings

        :param theDict: a dict instance of self.klass to be encoded
        :return: A encoded list of (key, value) pairs
        """

        if not isinstance(theDict, self.klass):
            raise RuntimeError(f'Expected instance of {type(self.klass)}, got {type(theDict)}')

        if self._doRecurse():
            theList = [(key, self.encodeItem(val)) for key,val in theDict.items()]
        else:
            theList = [(key, val) for key,val in theDict.items()]

        return theList

    def decode(self, theList):
        """Decode the list of (key,value) pairs; always recurse to decode values

        :param theList: list with (key,value) pairs to decode
        :return: the decoded list as a dict
        """
        # needs recursing for each (key, value) pair
        result = [(key, self.decodeItem(value)) for key, value in theList]
        theDict = dict(result)
        return theDict
# end class


class ListTraitJsonHandlerABC(ContainerJsonHandlerABC):
    """Abstract base class to handle recursion of list-like traits
    Each value of the (list must of CcpNmrJson (sub-)type
    """

    def getJsonItemHandler(self):
        """:return A jsonHandler instance for the item or None
        """
        if self.trait.itemTrait is not None:
            return self.trait.itemTrait.getJsonHandler(obj=self.obj)
        else:
            return None

    def encode(self, theList):
        """Encode thelist, optionally recursing depending on class / trait settings

        :param theList: a list instance of self.klass to be encoded
        :return: The encoded list
        """
        if not isinstance(theList, self.klass):
            raise RuntimeError(f'Expected instance of {type(self.klass)}, got {type(theList)}')

        if self._doRecurse():
            result = [self.encodeItem(item) for item in theList]
        else:
            result = [item for item in theList]

        return result

    def decode(self, theList):
        """Decode theList of encoded items; always recurse to decode items

        :param theList: list with items to decode
        :return: the decoded list
        """
        # needs decoding for each item in theList
        result = [self.decodeItem(item) for item in theList]
        return result
# end class


class CcpNmrJsonClassHandlerABC(TraitJsonHandlerBase):
    """Abstract base class to handle class-like traits of the CcpNmrJson (sub-)type
    """
    # #--------------------------------------------------------------------------------------------
    # # to be subclassed
    # #--------------------------------------------------------------------------------------------
    # klass = None
    # #--------------------------------------------------------------------------------------------
    # # end to be subclassed
    # #--------------------------------------------------------------------------------------------

    def encode(self, value):
        # convert klass, of (sub-)type CcpNmrJson

        # local imports to avoid circular dependencies
        from ccpn.util.traits.CcpNmrJson import CcpNmrJson

        if isinstance(value, CcpNmrJson):
            value = value._encode()

        return value

    def decode(self, value):
        # converting value to the relevant klass instance

        # local imports to avoid circular dependencies
        from ccpn.util.traits.CcpNmrJson import CcpNmrJson

        result = value
        # check if this encoded a CcpNmrJson type object
        if CcpNmrJson._isEncodedObject(value):
            theDict = dict(value)
            result = CcpNmrJson._newObjectFromDict(theDict)

        return result
